"""new fields in user model

Revision ID: 64eb19d097ab
Revises: 2ddd9e1978cd
Create Date: 2018-08-19 13:07:35.941923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eb19d097ab'
down_revision = '2ddd9e1978cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
